name: ASFHyP3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - sphinx
  - myst-parser
  - sphinx-autobuild
  - mkdocs
  - mkdocs-material
  - mkdocs-material-extensions
  - pip:
      - sphinx-material
      - mkdocs-gitsnippet-plugin
