name: ASFHyP3
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - pip
  # For documentation
  - mkdocs
  - mkdocs-material
  - mkdocs-material-extensions
  - pip:
      # For documentation
      - hyp3_sdk==0.3.3  # also pinned in docs/using/sdk.md
      - asf_tools==0.2.0  # also pinned in docs/tools/asf_tools.md
      - mkdocstrings
      - git+https://github.com/Jlrine2/mkdocs-gitsnippet-plugin.git
