name: ASFHyP3
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - pip
  # For SDK
  - importlib_metadata
  - requests
  - setuptools
  - setuptools_scm
  - wheel
  # For documentation
  - mkdocs
  - mkdocs-material
  - mkdocs-material-extensions
  - pip:
      # For documentation
      - mkdocstrings
      - git+https://github.com/Jlrine2/mkdocs-gitsnippet-plugin.git
