site_name: HyP3
site_url: https://ASFHyP3.github.io/
site_author: ASF APD/Tools Team
site_description: The Alaska Satellite Facility's Hybrid Pluggable Processing Pipeline
copyright: © <script>document.write(new Date().getFullYear())</script> Alaska Satellite Facility
google_analytics: ['UA-991100-5', 'search.asf.alaska.edu']

theme:
  name: "material"
  logo: images/HyP3-graphic-only.png
  favicon: images/favicon.ico
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.instant

repo_url: https://github.com/ASFHyP3
repo_name: ASF HyP3

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Ak_Satellite
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/ASFHyP3/community

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3

nav:
  - Home: index.md
  - Products:
      - Overview: products.md
      - Usage: usage.md
      - Product guides:
          - RTC Users Guide: guides/rtc_user.md
          - RTC ATBD: guides/rtc_atbd.md
  - Tutoials:
      - Overview: tutorials.md
  - Software:
      - Overview: software.md
      - HyP3: hyp3.md
      - SDK: sdk.md
      - hyp3lib: hyp3lib.md
      - GIS Tools: gis_tools.md
  - Plugins:
      - Overview: plugins.md
      - HyP3 GAMMA: plugins/gamma.md
      - HyP3 autoRIFT: plugins/autoRIFT.md
  - Contributing: contributing.md
