name: Deploy to Github.io

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build site and deploy
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          path: ASFHyP3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          activate-environment: ASFHyP3
          environment-file: ASFHyP3/conda-env.yml

      - name: test build of website
        if: github.ref != 'refs/heads/main'
        shell: bash -l {0}
        run: |
          cd ASFHyP3
          mkdocs build --verbose

      - uses: actions/checkout@v2
        if: github.ref == 'refs/heads/main'
        with:
          repository: ASFHyP3/ASFHyP3.github.io
          path: ASFHyP3.github.io
          token: ${{ secrets.TOOLS_BOT_PAK }}

      - name: deploy to github.io
        if: github.ref == 'refs/heads/main'
        shell: bash -l {0}
        run: |
          cd ASFHyP3.github.io
          mkdocs gh-deploy --config-file ../ASFHyP3/mkdocs.yml --remote-branch main
